version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: leaderboard_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Shree123
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: leaderboard_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: leaderboard_app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Shree123
      - POSTGRES_DB=leaderboard
      # Internal docker DNS names
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - PORT=8080
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_data:
